version: '3'
services:
  application1:
    build: .
    environment:
      - APP_NAME=Application One1
    ports:
      - "3001:3000"
  application2:
    build: .
    environment:
      - APP_NAME=Application Two
    ports:
      - "3002:3000"
  application3:
    build: .
    environment:
      - APP_NAME=Application Three
    ports:
      - "3003:3000"